version: "3.7"

services:
  the-book-pundit-apis:
    working_dir: /opt/app
    image: bahtou/the-book-pundit-apis-gr:latest
    logging:
      driver: fluentd
      options:
        fluentd-address: 0.0.0.0:24224
        tag: docker.apis
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - NODE_PORT=3001
      - SERVICE_API=gr
      - GOODREADS_KEY=st2TmgtgiCLegslyXYWA
    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints: [node.role == worker]
    networks:
      - the-book-pundit-service_api_net
      - the-book-pundit-service_monitor

networks:
  the-book-pundit-service_api_net:
    external: true
  the-book-pundit-service_monitor:
    external: true
